# -*- coding: utf-8 -*-
"""Build the English bond catalog from the Chinese v1.4 table (curated term-by-term)."""
import pandas as pd

SRC = r'D:\01\z_software\z_mine\01classification\01_键型总表_v1.4.tsv'
OUT = r'D:\01\Github\BOND\data\bond_catalog_v1.4.tsv'

df = pd.read_csv(SRC, encoding='utf-8-sig', sep='\t')

FAMILY = {'糖苷键族': 'Glycosidic', '酯键族': 'Ester', '酰胺·腈族': 'Amide-Nitrile',
          '烯炔键族': 'Alkene-Alkyne', '醚·环氧族': 'Ether-Epoxide', '硫键族': 'Sulfur',
          '碳-碳骨架键族': 'C-C skeleton'}
ESSENCE = {'O-糖苷键': 'O-glycosidic bond', 'C-糖苷键': 'C-glycosidic bond',
           'N-糖苷键': 'N-glycosidic bond', 'S-糖苷键': 'S-glycosidic bond',
           '羧酸酯键': 'carboxylic ester bond', '磷酸酯键': 'phosphate ester bond',
           '硫酸酯键': 'sulfate ester bond', '硫酯键': 'thioester bond',
           '酰胺键': 'amide bond', '腈键': 'nitrile bond', '烯键': 'alkene bond',
           '炔键': 'alkyne bond', '醚键': 'ether bond', '硫醚键': 'thioether bond',
           '二硫键': 'disulfide bond', '芳基C-C键': 'aryl C-C bond'}
DIRECTION = {'降解': 'degradation', '降解(氧化)': 'degradation (oxidative)',
             '降解(氧化+裂解)': 'degradation (oxidative + lyase)',
             '降解(水合)': 'degradation (hydration)', '合成': 'synthesis',
             '还原': 'reduction', '氧化裂解': 'oxidative cleavage',
             '氧化脱甲基': 'oxidative O-demethylation', '氧化开环': 'oxidative ring opening',
             '氧化': 'oxidation', '水合(弱)': 'hydration (weak)'}
GRADE_NOTE = {'A': 'dual official anchors (IUPAC term + dedicated EC entries)',
              'B': 'single anchor + literature (broad-specificity or substrate-specific enzyme)',
              'C': 'chemistry only; marker type, excluded from enzyme association'}

# curated per-code English names (chemical terminology, not machine-translated)
NAME = {
 'G01': 'O-beta-D-glucoside (aglycone-linked)', 'G02': 'O-beta-D-glucoside (sugar-chain-linked)',
 'G03': 'O-alpha-D-glucoside (incl. sugar chain)', 'G04': 'O-alpha-L-rhamnoside (aglycone-linked)',
 'G05': 'O-alpha-L-rhamnoside (sugar-chain/terminal)', 'G06': 'O-beta-D-galactoside (aglycone-linked)',
 'G07': 'O-beta-D-galactoside (sugar-chain)', 'G08': 'O-beta-D-xyloside (aglycone-linked)',
 'G09': 'O-beta-D-xyloside (sugar-chain)', 'G10': 'O-alpha-L-arabinoside (furanose/pyranose)',
 'G11': 'O-beta-D-mannoside (incl. sugar chain)', 'G12': 'O-beta-D-glucuronide',
 'G13': 'O-alpha-D-apioside', 'G14': 'O-glycoside (sugar species undetermined)',
 'G15': 'special disaccharide/rare-sugar glycoside', 'G16': 'C-glycoside (aryl C-sugar bond)',
 'G17': 'N-glycoside (nucleoside-type)', 'G18': 'S-glycoside (thioglycoside)',
 'E01': 'aliphatic carboxylic ester (open-chain)', 'E02': 'aromatic carboxylic ester (phenolic acid ester)',
 'E03': 'galloyl ester (hydrolyzable tannin-type)', 'E04': 'aromatic lactone (coumarin-type)',
 'E05': 'acyl sugar ester (1-O-acyl)', 'E06': 'phosphate ester', 'E07': 'sulfate ester',
 'E08': 'thioester', 'E09': 'aliphatic lactone (gamma/delta/macro)',
 'N01': 'amide (open-chain, non-peptide)', 'N02': 'lactam (cyclic amide)', 'N03': 'nitrile',
 'N04': 'peptide bond (amino-acid alpha-carbon context)',
 'A01': 'activated alkene (alpha,beta-unsaturated carbonyl)',
 'A02': 'cinnamoyl side-chain alkene (aryl-CH=CH-COX)',
 'A03': 'conjugated diene/polyene (incl. carotenoids)', 'A04': 'isolated alkene (non-activated)',
 'A05': 'alkyne (polyacetylene)', 'T01': 'methoxy ether', 'T02': 'alkyl/cyclic ether (non-methoxy)',
 'T03': 'aryl ether (diaryl/aryl-alkyl)', 'T04': 'epoxide (three-membered cyclic ether)',
 'T05': 'methylenedioxy bridge (O-CH2-O)', 'S01': 'thioether (C-S-C)', 'S02': 'disulfide (S-S)',
 'C01': 'aryl-aryl C-C bond (biphenyl/biflavonoid)', 'C02': 'lignan C6-C3 skeleton C-C (8-8)',
 'C03': 'prenyl C-C (aryl C5 side-chain)',
}
CTX = {
 'G01': 'sugar=beta-D-glucose; position=aglycone', 'G02': 'sugar=beta-D-glucose; position=sugar chain',
 'G03': 'sugar=alpha-D-glucose; position=aglycone/chain', 'G04': 'sugar=alpha-L-rhamnose; position=aglycone',
 'G05': 'sugar=alpha-L-rhamnose; position=sugar chain', 'G06': 'sugar=beta-D-galactose; position=aglycone',
 'G07': 'sugar=beta-D-galactose; position=sugar chain', 'G08': 'sugar=beta-D-xylose; position=aglycone',
 'G09': 'sugar=beta-D-xylose; position=sugar chain', 'G10': 'sugar=alpha-L-arabinose; position=aglycone/chain',
 'G11': 'sugar=beta-D-mannose; position=aglycone/chain', 'G12': 'sugar=beta-D-glucuronic acid; position=aglycone',
 'G13': 'sugar=alpha-D-apiose; position=aglycone/chain', 'G14': 'sugar=undetermined; position=undetermined',
 'G15': 'special disaccharide or rare sugar', 'G16': 'heteroatom=C (aromatic ring)',
 'G17': 'heteroatom=N (base)', 'G18': 'heteroatom=S',
 'E01': 'acyl=aliphatic; ring=open-chain', 'E02': 'acyl=aromatic (phenolic acid)',
 'E03': 'acyl=galloyl (tri-hydroxyphenyl)', 'E04': 'in-ring; fused=aromatic (coumarin-type)',
 'E05': 'alcohol side=sugar anomeric O', 'E06': 'phosphoryl', 'E07': 'sulfonyl',
 'E08': 'acyl-S', 'E09': 'in-ring; fused=none (gamma/delta/macro)',
 'N01': 'open-chain; N-context=non-peptide', 'N02': 'in-ring (lactam)',
 'N03': 'C triple-bond N', 'N04': 'open-chain; N-context=peptide (alpha-carbon)',
 'A01': 'conjugation=activated (enone)', 'A02': 'conjugation=aryl+alkene+carbonyl (cinnamoyl)',
 'A03': 'conjugation=diene/polyene', 'A04': 'conjugation=none (isolated)', 'A05': 'C triple-bond C',
 'T01': 'substituent=methyl', 'T02': 'substituent=alkyl/cyclic (non-aryl, non-methyl)',
 'T03': 'substituent=aryl', 'T04': 'ring=three-membered (epoxide)', 'T05': 'ring=methylenedioxy (non-sugar acetal)',
 'S01': 'C-S-C', 'S02': 'S-S',
 'C01': 'linkage=aryl-aryl (biphenyl)', 'C02': 'linkage=aryl-alkyl-aryl (lignan)', 'C03': 'linkage=aryl-prenyl',
}

out = pd.DataFrame({
 'code': df['编号'],
 'family': df['大类'].map(FAMILY),
 'bond_type': df['编号'].map(NAME),
 'bond_essence': df['键本质'].map(ESSENCE),
 'context_dimensions': df['编号'].map(CTX),
 'structural_definition': df['结构定义'],
 'smarts_essence': df['SMARTS要点'],
 'chemical_basis': df['化学依据'],
 'EC_anchor': df['酶学锚点EC'],
 'CAZy_or_KO': df['CAZy或KO'],
 'direction': df['方向'].map(lambda x: DIRECTION.get(str(x), str(x))),
 'evidence_grade': df['证据等级'],
 'grade_definition': df['证据等级'].map(GRADE_NOTE),
 'status': df['状态'].map({'正式': 'official', '标记型': 'marker-only'}),
})
# translate structural_definition / chemical_basis / EC_anchor / CAZy_or_KO per code
STRUCT = {
 'G01': 'glucose anomeric C1 (beta) linked via O to an aglycone',
 'G02': 'beta-O-glycosidic bond between glucose units (1->2/1->4/1->6)',
 'G03': 'alpha-configured anomeric O-glycosidic bond of glucose (incl. alpha(1->x) chains)',
 'G04': 'alpha-L-rhamnose C1 linked via O to an aglycone',
 'G05': 'alpha-L-rhamnose O-glycosidic bond at sugar-chain position (1->6/1->2)',
 'G06': 'beta-D-galactose C1-O-aglycone', 'G07': 'beta-galactose linkage within sugar chain',
 'G08': 'beta-D-xylose (pentose) C1-O-aglycone', 'G09': 'beta(1->4) xylose bond in xylan backbone',
 'G10': 'alpha-L-arabinose O-glycosidic bond (furanose or pyranose)',
 'G11': 'beta-D-mannose O-glycosidic bond (C2 epimer of glucose)',
 'G12': 'glucuronic acid C1-O-aglycone (C6 oxidized to COOH)',
 'G13': 'apiose (branched pentose) O-glycosidic bond', 'G14': 'sugar ring + exocyclic O, sugar identity/config undetermined',
 'G15': 'anomeric linkage of special disaccharides or rare sugars',
 'G16': 'direct C-C bond between sugar C1 and an aromatic carbon',
 'G17': 'anomeric C-N bond (purine/pyrimidine nucleoside)',
 'G18': 'anomeric C-S bond (glucosinolate-type)',
 'E01': 'R-C(=O)-O-R with aliphatic acyl carbon', 'E02': 'aryl-C(=O)-O-R (phenolic acid acyl)',
 'E03': '3,4,5-trihydroxybenzoyl-O-sugar/polyol', 'E04': 'ester O in-ring fused to an aromatic ring (2H-chromen-2-one type)',
 'E05': 'anomeric O-acyl on sugar (acyl directly on sugar O)', 'E06': 'P(=O)-O-C (phospho-mono/diester)',
 'E07': 'S(=O)2-O-C', 'E08': 'R-C(=O)-S-R',
 'N01': 'R-C(=O)-N(R)2 open-chain (excludes peptide and lactam)',
 'N02': 'C(=O)-N within a ring', 'N03': 'terminal R-C triple-bond N',
 'N04': 'CalphaH-C(=O)-N-CalphaH (both sides amino-acid alpha carbons)',
 'A01': 'C=C conjugated with C=O (Michael-acceptor beta-carbon)',
 'A02': 'aryl-CH=CH-C(=O)X (triple conjugation: aryl + alkene + carbonyl)',
 'A03': 'C=C-C=C (non-carbonyl conjugated diene or longer)',
 'A04': 'C=C without conjugation (fatty chain)', 'A05': 'C triple-bond C',
 'T01': 'O-CH3 (aryl or alkyl)', 'T02': 'C-O-C with both carbons non-aromatic (incl. terpene furan/pyran ring ethers)',
 'T03': 'ether O bonded to at least one aromatic carbon (excl. glycosidic bridge O)',
 'T04': 'three-membered C-C-O ring', 'T05': 'aromatic O-CH2-O acetal bridge (sesame-lignan type)',
 'S01': 'R-S-R', 'S02': 'R-S-S-R',
 'C01': 'direct C-C bond between two independent aromatic rings (amentoflavone-type biflavonoid)',
 'C02': 'Ar-CHx-CHx-Ar dibenzyl linkage (secoisolariciresinol-type)',
 'C03': 'aryl-C(C5 prenyl/isoprenyl) bond',
}
CHEM = {
 'G01': 'acetal bond (anomeric sp3 C, cyclic acetal); beta config + D-series stereochemistry',
 'G02': 'acetal bond; endo/exo positions of sugar chain',
 'G03': 'acetal bond; alpha configuration', 'G04': 'acetal bond; 6-deoxy + L-series configuration',
 'G05': 'acetal bond; terminal position', 'G06': 'acetal bond; beta configuration',
 'G07': 'acetal bond', 'G08': 'acetal bond; pentose backbone', 'G09': 'acetal bond',
 'G10': 'acetal bond; alpha-L pentose', 'G11': 'acetal bond; C2 epimeric configuration',
 'G12': 'acetal bond; C6 carboxylated sugar', 'G13': 'acetal bond; branched pentose',
 'G14': 'acetal bond established; stereochemistry missing', 'G15': 'acetal bond; special sugar-pair linkage',
 'G16': 'aryl sp2 - sugar sp3 C-C bond; resistant to common glycosidases',
 'G17': 'N-acetal bond; nucleoside linkage', 'G18': 'S-acetal bond',
 'E01': 'acyl-O bond; carboxylic acid leaving group (pKa 4-5)', 'E02': 'aryl conjugation lowers acyl-carbon electron density',
 'E03': 'aryl + tri-phenol substituted acyl ester', 'E04': 'intramolecular ester; aromatic fusion shifts carbonyl',
 'E05': 'anomeric O-acyl (ester, not glycoside)', 'E06': 'phosphoryl-O bond', 'E07': 'sulfonyl-O bond',
 'E08': 'thioacyl bond', 'E09': 'intramolecular ester; ring-opening equilibrium',
 'N01': 'C-N amide bond; resonance-stabilized (15-20 kcal/mol)', 'N02': 'cyclic amide; resonance-stabilized',
 'N03': 'sp-hybridized C triple-bond N; large dipole', 'N04': 'C-N amide bond; dedicated EC 3.4 subclass (557 entries)',
 'A01': 'conjugation lowers HOMO-LUMO gap; electrophilic beta-carbon', 'A02': 'triple conjugation aryl+ene+carbonyl',
 'A03': 'conjugated polyene; oxidative-cleavage site', 'A04': 'no conjugation; unremarkable reactivity',
 'A05': 'sp-hybridized; addition chemistry', 'T01': 'alkyl ether; hydrolysis needs pKa-16 leaving group',
 'T02': 'alkyl ether; inert bond', 'T03': 'aryl ether; CYP oxidative cleavage',
 'T04': 'strained three-membered ether; nucleophilic ring opening', 'T05': 'non-sugar cyclic acetal; CYP demethylenation',
 'S01': 'low-electronegativity S; readily oxidized to sulfoxide', 'S02': 'redox-sensitive bond',
 'C01': 'no heteroatom, no polarization; among the most inert bonds (laccase/peroxidase radical chemistry)',
 'C02': 'aryl-alkyl C-C; radical substrate', 'C03': 'prenyl-aryl C-C',
}
EC_FIX = {
 'G01': 'EC 3.2.1.21', 'G02': 'EC 3.2.1.21 / 3.2.1.4', 'G03': 'EC 3.2.1.20', 'G04': 'EC 3.2.1.40',
 'G05': 'EC 3.2.1.40', 'G06': 'EC 3.2.1.23', 'G07': 'EC 3.2.1.23', 'G08': 'EC 3.2.1.37',
 'G09': 'EC 3.2.1.37', 'G10': 'EC 3.2.1.55', 'G11': 'EC 3.2.1.25', 'G12': 'EC 3.2.1.31',
 'G13': 'EC 3.2.1.- (no dedicated entry; pending)', 'G14': 'EC 3.2.1.- (sugar-dependent)',
 'G15': 'EC 3.2.1.x (sugar-dependent; trehalase GH37 etc.)', 'G16': 'EC 1.1.3.50 (C-glycoside oxidase) / 4.1.99.28 (deglycosidase)',
 'G17': 'EC 3.2.2.1 / 3.2.2.2', 'G18': 'EC 3.2.1.147',
 'E01': 'EC 3.1.1.1', 'E02': 'EC 3.1.1.73', 'E03': 'EC 3.1.1.20', 'E04': 'EC 3.1.1.35',
 'E05': 'EC 3.1.1.x', 'E06': 'EC 3.1.3.1 / 3.1.4.1', 'E07': 'EC 3.1.6.1', 'E08': 'EC 3.1.2.x',
 'E09': 'EC 3.1.1.17 (gluconolactonase) / 3.1.1.25 (1,4-lactonase)',
 'N01': 'EC 3.5.1.x', 'N02': 'EC 3.5.2.x', 'N03': 'EC 3.5.5.1', 'N04': 'EC 3.4.x (peptidases/proteases)',
 'A01': 'EC 1.3.1.x (OYE-family ene reductases)', 'A02': 'EC 1.3.1.x (hydroxycinnamate reductases)',
 'A03': 'EC 1.13.11.x (dioxygenases; CCO family)', 'A04': 'none dedicated (hydratases EC 4.2.1 individually)',
 'A05': 'rare (alkyne hydratase-type)', 'T01': 'EC 1.14.13.x (O-demethylating CYPs)',
 'T02': 'EC 3.3.2 (rare) / 1.14 CYP oxidation', 'T03': 'EC 1.14.13.x', 'T04': 'EC 3.3.2.3 (epoxide hydrolase)',
 'T05': 'EC 1.14.13.x (CYP demethylenation)', 'S01': 'EC 3.3.1 (rare) / FMO oxidation',
 'S02': 'EC 1.8.4.x (thioredoxin/glutathione systems)', 'C01': 'EC 1.10.3.2 (laccase) / 1.11.1 (peroxidase)',
 'C02': 'EC 1.10.3 / 1.11.1 (radical oxidative cleavage)', 'C03': 'EC 2.5.1.x (prenyltransferases, synthesis direction)',
}
CAZY = {
 'G01': 'GH1/GH3 (K01188)', 'G02': 'GH1/GH3', 'G03': 'GH13 (K01187)', 'G04': 'GH78 (K05989)',
 'G05': 'GH78/GH106', 'G06': 'GH2/GH35 (K01190)', 'G07': 'GH2/GH35', 'G08': 'GH3/GH39/GH43 (K01198)',
 'G09': 'GH10/GH11', 'G10': 'GH43/GH51 (K01207)', 'G11': 'GH2', 'G12': 'GH2/GH79 (K01498)',
 'G13': 'no dedicated family in reference tables', 'G14': 'sugar-dependent', 'G15': 'GH37 (trehalase) etc.',
 'G16': 'atypical (literature-level; K26081 carA / K26912 carB)', 'G17': 'GH3 (partial; K01241)',
 'G18': 'GH1 (myrosinase)', 'E01': 'CE family / K01054', 'E02': 'CE1/CE6 (K03326)', 'E03': 'tannase family',
 'E04': 'esterases (K01063)', 'E05': 'carboxylesterases', 'E06': 'EC 3.1.3.26 phytase (K01077)',
 'E07': 'sulfatases (K01132)', 'E08': 'thioesterases', 'E09': 'CE / lactonases',
 'N01': 'K01254 / proteases', 'N02': 'lactamases', 'N03': 'nitrilase (K01507)',
 'N04': 'MEROPS system / K01254', 'A01': 'OYE family (K00208)', 'A02': 'OYE family',
 'A03': 'CCO family (K02291)', 'A04': 'individual hydratases', 'A05': '-',
 'T01': 'CYP (K00484)', 'T02': 'CYP oxidation', 'T03': 'CYP', 'T04': 'epoxide hydrolase (K10535)',
 'T05': 'CYP', 'S01': 'flavin monooxygenases', 'S02': 'thioredoxin (K00384)',
 'C01': 'laccase (K00446) / peroxidase (K00449)', 'C02': 'laccase/peroxidase', 'C03': 'prenyltransferase',
}
NOTE = {
 'G01': '207 compounds in reference curation', 'G02': 'terminal sugars cleaved by exo-glycosidases',
 'G03': 'starch/sucrose-type linkages', 'G04': '35 compounds in reference curation',
 'G05': 'outer sugar of rutin-type diglycosides', 'G06': '', 'G07': '', 'G08': '',
 'G09': 'xylan backbone', 'G10': 'arabinofuranosidase context', 'G11': '', 'G12': '',
 'G13': 'marked pending in reference curation', 'G14': 'upgrade target of the OPSIN name bridge (631 bonds)',
 'G15': 'merged low-frequency row', 'G16': '56 compounds without direct hydrolase in reference curation; '
        'official anchors confirmed (EC 1.1.3.50/4.1.99.28); demonstrated substrate carminate-type C-glycosides',
 'G17': 'nucleoside hydrolases', 'G18': 'Brassicaceae hallmark; rare in studied data',
 'E01': 'lipases (EC 3.1.1.3) also apply', 'E02': 'feruloyl esterases specifically cleave phenolic acid esters',
 'E03': 'hallmark of hydrolyzable tannins', 'E04': 'coumarins / terpene lactones',
 'E05': '22+5 acyl-sugar bonds in reference curation', 'E06': 'phytate (feed) / phospholipids',
 'E07': 'sulfate group of glucosinolates', 'E08': 'rare in natural products (polyketides)',
 'N01': 'alkaloid amides / peptides', 'N02': 'some alkaloids', 'N03': 'cyanogenic glycoside aglycones',
 'N04': 'added in v1.1: peptide bond split from N01 (EC 3.4 is an independent official subclass)',
 'A01': 'chalcones / enones', 'A02': 'phenylpropanoid hallmark side chain',
 'A03': 'source of vomifoliol-type aglycones', 'A04': 'background bond type; excluded from enzyme association',
 'A05': 'polyacetylene natural products; marker-only', 'T01': 'O-demethylation to catechols documented',
 'T02': 'common in terpene ring ethers; sugar in-ring ethers excluded from counts',
 'T03': 'lignans / furanocoumarins', 'T04': 'terpene epoxides', 'T05': 'sesamin/piperine hallmark',
 'S01': 'volatile sulfur compounds', 'S02': 'glutathione / peptides',
 'C01': 'Platycladus hallmark: biflavonoid amentoflavone-type linkage',
 'C02': 'secoisolariciresinol-type lignan skeleton', 'C03': 'synthesis-direction anchor; weak degradation evidence',
}
out['structural_definition'] = out['code'].map(STRUCT)
out['chemical_basis'] = out['code'].map(CHEM)
out['EC_anchor'] = out['code'].map(EC_FIX)
out['CAZy_or_KO'] = out['code'].map(CAZY)
out['notes'] = out['code'].map(NOTE)
out = out[['code','family','bond_type','bond_essence','context_dimensions','structural_definition',
           'smarts_essence','chemical_basis','EC_anchor','CAZy_or_KO','direction',
           'evidence_grade','grade_definition','status','notes']]
out.to_csv(OUT, sep='\t', index=False, encoding='utf-8')
print('English catalog written:', len(out), 'rows')
